// Generated by Selenium IDE

package TradeFinance;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class Test777 {
private WebDriver driver;
//private Map<String, Object> vars;
//        JavascriptExecutor js;
@Before
public void setUp(){
  driver=new ChromeDriver();
      //  js=(JavascriptExecutor)driver;
      //  vars=new HashMap<String, Object>();
        }
@After
public void tearDown(){
        //driver.quit();
        }
@Test
public void Test777(){
        /*driver.get("google.com");
        driver.manage().window().setSize(new Dimension(1936,1056));
        driver.findElement(By.cssSelector("#\\__BVID__81___BV_modal_body_ .icon-text")).click();
        driver.findElement(By.cssSelector(".btn-outline-primary:nth-child(2) > span")).click();
        driver.findElement(By.cssSelector(".btn-success:nth-child(1) > .icon-text")).click();
        driver.findElement(By.cssSelector(".float-left > .icon-text")).click();
        driver.findElement(By.cssSelector("#\\__BVID__200___BV_modal_footer_ .btn")).click();
        driver.findElement(By.cssSelector(".btn-info > .icon-text")).click();
        driver.findElement(By.linkText("Выход")).click(); */
        }
        }
