// Generated by Selenium IDE

//Открытие счета

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
 // @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1Test() {
    driver.get("http://77.244.210.158:8082/");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.findElement(By.id("selectAddress")).click();
    {
      WebElement dropdown = driver.findElement(By.id("selectAddress"));
      dropdown.findElement(By.xpath("//option[. = '0x7a6bd923d6f951d010bc899c96b2411f790ef789 - MANAGER']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Счета")).click();
    driver.findElement(By.cssSelector(".fa-plus-square")).click();
    driver.findElement(By.id("accType")).click();
    {
      WebElement dropdown = driver.findElement(By.id("accType"));
      dropdown.findElement(By.xpath("//option[. = 'L10 - Владелец']")).click();
    }
    driver.findElement(By.cssSelector("#accType > option:nth-child(4)")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.id("number")).click();
    driver.findElement(By.id("number")).sendKeys("1");
    driver.findElement(By.id("reasonDoc-openAcc-0")).click();
    {
      WebElement dropdown = driver.findElement(By.id("reasonDoc-openAcc-0"));
      dropdown.findElement(By.xpath("//option[. = '7: WHixZmxqUho.jpg [бтбь] от Тыгыдык №б/н']")).click();
    }
    driver.findElement(By.cssSelector("#reasonDoc-openAcc-0 > option:nth-child(3)")).click();
    driver.findElement(By.id("reasonDoc-mortgageNew-0")).click();
    {
      WebElement dropdown = driver.findElement(By.id("reasonDoc-mortgageNew-0"));
      dropdown.findElement(By.xpath("//option[. = '7: WHixZmxqUho.jpg [бтбь] от Тыгыдык №б/н']")).click();
    }
    driver.findElement(By.cssSelector("#reasonDoc-mortgageNew-0 > option:nth-child(3)")).click();
    driver.findElement(By.id("reasonDoc-ownerRequest-0")).click();
    {
      WebElement dropdown = driver.findElement(By.id("reasonDoc-ownerRequest-0"));
      dropdown.findElement(By.xpath("//option[. = '7: WHixZmxqUho.jpg [бтбь] от Тыгыдык №б/н']")).click();
    }
    driver.findElement(By.cssSelector("#reasonDoc-ownerRequest-0 > option:nth-child(3)")).click();
    driver.findElement(By.id("reasonDoc-changeAgreement-0")).click();
    {
      WebElement dropdown = driver.findElement(By.id("reasonDoc-changeAgreement-0"));
      dropdown.findElement(By.xpath("//option[. = '7: WHixZmxqUho.jpg [бтбь] от Тыгыдык №б/н']")).click();
    }
    driver.findElement(By.cssSelector("#reasonDoc-changeAgreement-0 > option:nth-child(3)")).click();
    driver.findElement(By.id("reasonDoc-mortgageWithdrawal-0")).click();
    {
      WebElement dropdown = driver.findElement(By.id("reasonDoc-mortgageWithdrawal-0"));
      dropdown.findElement(By.xpath("//option[. = '7: WHixZmxqUho.jpg [бтбь] от Тыгыдык №б/н']")).click();
    }
    driver.findElement(By.cssSelector("#reasonDoc-mortgageWithdrawal-0 > option:nth-child(3)")).click();
    driver.findElement(By.name("open")).click();
  }
}
