package com.exemple.test;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class StatementTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void statement() {
    driver.get("http://5.178.84.102/cbg/");
    driver.manage().window().setSize(new Dimension(1919, 1039));
    driver.findElement(By.cssSelector("#\\__BVID__81___BV_modal_body_ .icon-text")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#\\__BVID__81___BV_modal_body_ .icon-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".btn-success:nth-child(1) > .icon-text")).click();
    driver.findElement(By.cssSelector(".float-left > .icon-text")).click();
    driver.findElement(By.cssSelector("#\\__BVID__196___BV_modal_footer_ .icon-text")).click();
    driver.findElement(By.cssSelector(".card-body > .btn > .icon-text")).click();
    driver.findElement(By.id("__BVID__304")).click();
    driver.findElement(By.id("__BVID__304")).sendKeys("2019-11-26");
    driver.findElement(By.id("__BVID__305")).click();
    driver.findElement(By.id("__BVID__305")).sendKeys("777");
    driver.findElement(By.id("__BVID__306")).click();
  }
}
