package com.exemple.test;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class TestTF333Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testTF333() {
    driver.get("http://5.178.84.102/cbg/");
    driver.manage().window().setSize(new Dimension(1920, 1040));
    driver.findElement(By.cssSelector("#\\__BVID__33___BV_modal_body_ .icon-text")).click();
    driver.findElement(By.cssSelector(".btn-outline-primary:nth-child(2) > span")).click();
    driver.findElement(By.cssSelector(".btn-success:nth-child(1) > .icon-text")).click();
    driver.findElement(By.cssSelector(".float-left > .icon-text")).click();
    driver.findElement(By.cssSelector("#\\__BVID__153___BV_modal_footer_ .fa-icon")).click();
    driver.findElement(By.cssSelector(".btn-info > .icon-text")).click();
  }
}
